(*******************************************************************************)
(*  Vcs - a Versatile OCaml Library for Git Operations                         *)
(*  Copyright (C) 2024 Mathieu Barbin <mathieu.barbin@gmail.com>               *)
(*                                                                             *)
(*  This file is part of Vcs.                                                  *)
(*                                                                             *)
(*  Vcs is free software; you can redistribute it and/or modify it under       *)
(*  the terms of the GNU Lesser General Public License as published by the     *)
(*  Free Software Foundation either version 3 of the License, or any later     *)
(*  version, with the LGPL-3.0 Linking Exception.                              *)
(*                                                                             *)
(*  Vcs is distributed in the hope that it will be useful, but WITHOUT ANY     *)
(*  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS  *)
(*  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License and    *)
(*  the file `NOTICE.md` at the root of this repository for more details.      *)
(*                                                                             *)
(*  You should have received a copy of the GNU Lesser General Public License   *)
(*  and the LGPL-3.0 Linking Exception along with this library. If not, see    *)
(*  <http://www.gnu.org/licenses/> and <https://spdx.org>, respectively.       *)
(*******************************************************************************)

let values = [ Vcs.Path_in_repo.v "foo.txt"; Vcs.Path_in_repo.v "bar/baz.ml" ]

let%expect_test "hash" =
  Hash_test.run (module Vcs.Path_in_repo) (module Vcs_base.Vcs.Path_in_repo) values;
  [%expect
    {|
    (((value foo.txt))
     ((stdlib_hash   836355526)
      (vcs_hash      836355526)
      (vcs_base_hash 836355526)))
    (((value foo.txt)
      (seed  0))
     ((stdlib_hash   836355526)
      (vcs_hash      836355526)
      (vcs_base_hash 836355526)))
    (((value foo.txt)
      (seed  42))
     ((stdlib_hash   444099220)
      (vcs_hash      444099220)
      (vcs_base_hash 444099220)))
    (((value bar/baz.ml))
     ((stdlib_hash   615308050)
      (vcs_hash      615308050)
      (vcs_base_hash 615308050)))
    (((value bar/baz.ml)
      (seed  0))
     ((stdlib_hash   615308050)
      (vcs_hash      615308050)
      (vcs_base_hash 615308050)))
    (((value bar/baz.ml)
      (seed  42))
     ((stdlib_hash   922480314)
      (vcs_hash      922480314)
      (vcs_base_hash 922480314)))
    |}];
  ()
;;
