(*******************************************************************************)
(*  Vcs - a Versatile OCaml Library for Git Operations                         *)
(*  Copyright (C) 2024-2025 Mathieu Barbin <mathieu.barbin@gmail.com>          *)
(*                                                                             *)
(*  This file is part of Vcs.                                                  *)
(*                                                                             *)
(*  Vcs is free software; you can redistribute it and/or modify it under       *)
(*  the terms of the GNU Lesser General Public License as published by the     *)
(*  Free Software Foundation either version 3 of the License, or any later     *)
(*  version, with the LGPL-3.0 Linking Exception.                              *)
(*                                                                             *)
(*  Vcs is distributed in the hope that it will be useful, but WITHOUT ANY     *)
(*  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS  *)
(*  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License and    *)
(*  the file `NOTICE.md` at the root of this repository for more details.      *)
(*                                                                             *)
(*  You should have received a copy of the GNU Lesser General Public License   *)
(*  and the LGPL-3.0 Linking Exception along with this library. If not, see    *)
(*  <http://www.gnu.org/licenses/> and <https://spdx.org>, respectively.       *)
(*******************************************************************************)

let values = [ Vcs.User_handle.v "john-doe"; Vcs.User_handle.v "jane-doe" ]

let%expect_test "hash" =
  Hash_test.run (module Vcs.User_handle) (module Volgo_base.Vcs.User_handle) values;
  [%expect
    {|
    (((value john-doe))
     ((stdlib_hash   152607077)
      (vcs_hash      152607077)
      (vcs_base_hash 152607077)))
    (((value john-doe)
      (seed  0))
     ((stdlib_hash   152607077)
      (vcs_hash      152607077)
      (vcs_base_hash 152607077)))
    (((value john-doe)
      (seed  42))
     ((stdlib_hash   80938851)
      (vcs_hash      80938851)
      (vcs_base_hash 80938851)))
    (((value jane-doe))
     ((stdlib_hash   209935393)
      (vcs_hash      209935393)
      (vcs_base_hash 209935393)))
    (((value jane-doe)
      (seed  0))
     ((stdlib_hash   209935393)
      (vcs_hash      209935393)
      (vcs_base_hash 209935393)))
    (((value jane-doe)
      (seed  42))
     ((stdlib_hash   414759229)
      (vcs_hash      414759229)
      (vcs_base_hash 414759229)))
    |}];
  ()
;;
