(*******************************************************************************)
(*  Vcs - a Versatile OCaml Library for Git Operations                         *)
(*  Copyright (C) 2024-2025 Mathieu Barbin <mathieu.barbin@gmail.com>          *)
(*                                                                             *)
(*  This file is part of Vcs.                                                  *)
(*                                                                             *)
(*  Vcs is free software; you can redistribute it and/or modify it under       *)
(*  the terms of the GNU Lesser General Public License as published by the     *)
(*  Free Software Foundation either version 3 of the License, or any later     *)
(*  version, with the LGPL-3.0 Linking Exception.                              *)
(*                                                                             *)
(*  Vcs is distributed in the hope that it will be useful, but WITHOUT ANY     *)
(*  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS  *)
(*  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License and    *)
(*  the file `NOTICE.md` at the root of this repository for more details.      *)
(*                                                                             *)
(*  You should have received a copy of the GNU Lesser General Public License   *)
(*  and the LGPL-3.0 Linking Exception along with this library. If not, see    *)
(*  <http://www.gnu.org/licenses/> and <https://spdx.org>, respectively.       *)
(*******************************************************************************)

let values = [ Vcs.Tag_name.v "my-tag"; Vcs.Tag_name.v "v0.0.1"; Vcs.Tag_name.v "1.2" ]

let%expect_test "hash" =
  Hash_test.run (module Vcs.Tag_name) (module Vcs_base.Vcs.Tag_name) values;
  [%expect
    {|
    (((value my-tag))
     ((stdlib_hash   865032536)
      (vcs_hash      865032536)
      (vcs_base_hash 865032536)))
    (((value my-tag)
      (seed  0))
     ((stdlib_hash   865032536)
      (vcs_hash      865032536)
      (vcs_base_hash 865032536)))
    (((value my-tag)
      (seed  42))
     ((stdlib_hash   809141036)
      (vcs_hash      809141036)
      (vcs_base_hash 809141036)))
    (((value v0.0.1))
     ((stdlib_hash   803999042)
      (vcs_hash      803999042)
      (vcs_base_hash 803999042)))
    (((value v0.0.1)
      (seed  0))
     ((stdlib_hash   803999042)
      (vcs_hash      803999042)
      (vcs_base_hash 803999042)))
    (((value v0.0.1)
      (seed  42))
     ((stdlib_hash   682119237)
      (vcs_hash      682119237)
      (vcs_base_hash 682119237)))
    (((value 1.2))
     ((stdlib_hash   968236532)
      (vcs_hash      968236532)
      (vcs_base_hash 968236532)))
    (((value 1.2)
      (seed  0))
     ((stdlib_hash   968236532)
      (vcs_hash      968236532)
      (vcs_base_hash 968236532)))
    (((value 1.2)
      (seed  42))
     ((stdlib_hash   285020915)
      (vcs_hash      285020915)
      (vcs_base_hash 285020915)))
    |}];
  ()
;;
