(*******************************************************************************)
(*  Vcs - a Versatile OCaml Library for Git Operations                         *)
(*  Copyright (C) 2024 Mathieu Barbin <mathieu.barbin@gmail.com>               *)
(*                                                                             *)
(*  This file is part of Vcs.                                                  *)
(*                                                                             *)
(*  Vcs is free software; you can redistribute it and/or modify it under       *)
(*  the terms of the GNU Lesser General Public License as published by the     *)
(*  Free Software Foundation either version 3 of the License, or any later     *)
(*  version, with the LGPL-3.0 Linking Exception.                              *)
(*                                                                             *)
(*  Vcs is distributed in the hope that it will be useful, but WITHOUT ANY     *)
(*  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS  *)
(*  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License and    *)
(*  the file `NOTICE.md` at the root of this repository for more details.      *)
(*                                                                             *)
(*  You should have received a copy of the GNU Lesser General Public License   *)
(*  and the LGPL-3.0 Linking Exception along with this library. If not, see    *)
(*  <http://www.gnu.org/licenses/> and <https://spdx.org>, respectively.       *)
(*******************************************************************************)

let values = [ Vcs.User_name.v "John Doe"; Vcs.User_name.v "Jane Doe" ]

let%expect_test "hash" =
  Hash_test.run (module Vcs.User_name) (module Vcs_base.Vcs.User_name) values;
  [%expect
    {|
    (((value "John Doe"))
     ((stdlib_hash   719227130)
      (vcs_hash      719227130)
      (vcs_base_hash 719227130)))
    (((value "John Doe")
      (seed  0))
     ((stdlib_hash   719227130)
      (vcs_hash      719227130)
      (vcs_base_hash 719227130)))
    (((value "John Doe")
      (seed  42))
     ((stdlib_hash   81441934)
      (vcs_hash      81441934)
      (vcs_base_hash 81441934)))
    (((value "Jane Doe"))
     ((stdlib_hash   659235483)
      (vcs_hash      659235483)
      (vcs_base_hash 659235483)))
    (((value "Jane Doe")
      (seed  0))
     ((stdlib_hash   659235483)
      (vcs_hash      659235483)
      (vcs_base_hash 659235483)))
    (((value "Jane Doe")
      (seed  42))
     ((stdlib_hash   443135183)
      (vcs_hash      443135183)
      (vcs_base_hash 443135183)))
    |}];
  ()
;;
