(*******************************************************************************)
(*  Vcs - a Versatile OCaml Library for Git Operations                         *)
(*  Copyright (C) 2024-2025 Mathieu Barbin <mathieu.barbin@gmail.com>          *)
(*                                                                             *)
(*  This file is part of Vcs.                                                  *)
(*                                                                             *)
(*  Vcs is free software; you can redistribute it and/or modify it under       *)
(*  the terms of the GNU Lesser General Public License as published by the     *)
(*  Free Software Foundation either version 3 of the License, or any later     *)
(*  version, with the LGPL-3.0 Linking Exception.                              *)
(*                                                                             *)
(*  Vcs is distributed in the hope that it will be useful, but WITHOUT ANY     *)
(*  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS  *)
(*  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License and    *)
(*  the file `NOTICE.md` at the root of this repository for more details.      *)
(*                                                                             *)
(*  You should have received a copy of the GNU Lesser General Public License   *)
(*  and the LGPL-3.0 Linking Exception along with this library. If not, see    *)
(*  <http://www.gnu.org/licenses/> and <https://spdx.org>, respectively.       *)
(*******************************************************************************)

let values = [ Vcs.Repo_root.v "/tmp/foo"; Vcs.Repo_root.v "/home/user/dev/repo" ]

let%expect_test "hash" =
  Hash_test.run (module Vcs.Repo_root) (module Vcs_base.Vcs.Repo_root) values;
  [%expect
    {|
    (((value /tmp/foo))
     ((stdlib_hash   300202224)
      (vcs_hash      300202224)
      (vcs_base_hash 300202224)))
    (((value /tmp/foo)
      (seed  0))
     ((stdlib_hash   300202224)
      (vcs_hash      300202224)
      (vcs_base_hash 300202224)))
    (((value /tmp/foo)
      (seed  42))
     ((stdlib_hash   202387283)
      (vcs_hash      202387283)
      (vcs_base_hash 202387283)))
    (((value /home/user/dev/repo))
     ((stdlib_hash   793408912)
      (vcs_hash      793408912)
      (vcs_base_hash 793408912)))
    (((value /home/user/dev/repo)
      (seed  0))
     ((stdlib_hash   793408912)
      (vcs_hash      793408912)
      (vcs_base_hash 793408912)))
    (((value /home/user/dev/repo)
      (seed  42))
     ((stdlib_hash   628866208)
      (vcs_hash      628866208)
      (vcs_base_hash 628866208)))
    |}];
  ()
;;
