(*******************************************************************************)
(*  Vcs - a Versatile OCaml Library for Git Operations                         *)
(*  Copyright (C) 2024-2025 Mathieu Barbin <mathieu.barbin@gmail.com>          *)
(*                                                                             *)
(*  This file is part of Vcs.                                                  *)
(*                                                                             *)
(*  Vcs is free software; you can redistribute it and/or modify it under       *)
(*  the terms of the GNU Lesser General Public License as published by the     *)
(*  Free Software Foundation either version 3 of the License, or any later     *)
(*  version, with the LGPL-3.0 Linking Exception.                              *)
(*                                                                             *)
(*  Vcs is distributed in the hope that it will be useful, but WITHOUT ANY     *)
(*  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS  *)
(*  FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License and    *)
(*  the file `NOTICE.md` at the root of this repository for more details.      *)
(*                                                                             *)
(*  You should have received a copy of the GNU Lesser General Public License   *)
(*  and the LGPL-3.0 Linking Exception along with this library. If not, see    *)
(*  <http://www.gnu.org/licenses/> and <https://spdx.org>, respectively.       *)
(*******************************************************************************)

let values = [ Vcs.File_contents.create ""; Vcs.File_contents.create "Hello" ]

let%expect_test "hash" =
  Hash_test.run (module Vcs.File_contents) (module Volgo_base.Vcs.File_contents) values;
  [%expect
    {|
    (((value ""))
     ((stdlib_hash   0)
      (vcs_hash      0)
      (vcs_base_hash 0)))
    (((value "")
      (seed  0))
     ((stdlib_hash   0)
      (vcs_hash      0)
      (vcs_base_hash 0)))
    (((value "")
      (seed  42))
     ((stdlib_hash   142593372)
      (vcs_hash      142593372)
      (vcs_base_hash 142593372)))
    (((value Hello))
     ((stdlib_hash   200495445)
      (vcs_hash      200495445)
      (vcs_base_hash 200495445)))
    (((value Hello)
      (seed  0))
     ((stdlib_hash   200495445)
      (vcs_hash      200495445)
      (vcs_base_hash 200495445)))
    (((value Hello)
      (seed  42))
     ((stdlib_hash   825079905)
      (vcs_hash      825079905)
      (vcs_base_hash 825079905)))
    |}];
  ()
;;
